### PR TITLE
add trapExit function to properly cleanup tmp directories

### PR DESCRIPTION
**Pull request by kshychko**
I added trapExit to each build script separately, but probably it should a utility function with the following parameters:

1. directory to be removed
2. exit code to returned
3. additional optional command to be executed before removal (like `nvm deactivate`)

This would allow us to re-use the function in other scripts.

### CODE REVIEW

**Comment by ml019** [comment]
The trap handler handles exceptions, so the cleanup needs to be incorporated into it. For instance, if the script is running and it gets a hup, the trap handler will execute regardless of where the script was when the signal came in.

With the use of functions, the main flow should always exit cleanly, so then its even more important the trap handler do any cleanup as its only likely to run on an unexpected signal.

**Comment by kshychko** [comment]
The problem with trap that it doesn't have access to variables defined in the main function - `NVM_DIR` or `venv_dir`, so it actually does nothing at the moment. It must be working fine for the scripts without a seaparate function use, but it doesn't clean up the code tmp directories for the Python and JS builds.
we could export the variables, but in this case they might affect parallel builds.

**Comment by ml019** [comment]
Is one option to make them global?

I would expect the normal flow to be doing the cleanup anyway rather than relying on the EXIT trap.

**Comment by ml019** [comment]
@kshychko Thoughts?

**Comment by roleyfoley** [comment]
The problem with exporting ( i'm assuming that's what you are calling global) them is that if you had two python or npm builds running at once they would overlap across the nvm or venv_dir and since each dir has the potential to have different code versions running it could get messy quick

**Comment by ml019** [comment]
Exports only work downwards though. Two separate builds would each be running their own build script

**Pull request closed without merging**
